### ISSUE TITLE
Improve UX

### ISSUE THREAD

**Issue by oliverbarnes** [liquidvotingio/decidim-liquidvoting#9]
We need to make the integration visually more seamless. Things I can think of, not exhaustive:

- create/delete delegation buttons, as well as delegates pull down should follow Decidim styling
- create delegation button should disappear when a delegation already exists, leaving only the delegation deletion button. Or we could have a single button for both creation and deletion
- delegation status should be a visually nice blurb

Any other ideas?

**Comment by jinjagit** [comment]
Sounds good for delegation.  
 
- For voting, do we want the current voting result to be displayed or not until some period elapses?  
- Do we also want to hid any voting button(s) if a relevant delegation already exists?

**Comment by oliverbarnes** [comment]
> - For voting, do we want the current voting result to be displayed or not until some period elapses?

I think we do, current decidim-proposals functionality shows the result (number of supports) already, right above the support button.

Regarding voting period, that's good you brought it up - it's something we need to look into and see how delegation-proposals handles that. The API doesn't yet have the voting freeze flag yet, but if that's handled client-side (say by hiding the voting interface after a deadline), it'd be good enough UX-wise.

> - Do we also want to hid any voting button(s) if a relevant delegation already exists?

I'd say not, delegators should still be able to override the delegation by voting, if they choose. UX-wise it might need some clear signaling, say when mouse-overing the voting button and showing a tooltip blurb explaining the vote will override the delegation.

I know this interface interaction starts getting complex. Could be worth mocking it up to previews the different scenarios, before getting ourselves into a js/css mess

**Comment by jinjagit** [comment]
A good next step is to make our current delegation state detection more robust, by not simply using the session[:delegated-to] to value (which may not exist). Something like this logic:  
```
If session delegated_to = nil
  -> check api & set to value or :none (do in view for now, and rethink later)
If session delegated_to = :none { we are in the no delegation exists case }
If session delegated_to = value { we are in the delegation exists case, and have access to the delegation info. }
```
For now, it is probably best to do this all in the view (using ERB), and later think about if/how to refactor some/all to controller/helper file(s).  
  
Then, we could do the same thing for the vote button display (which I have already got half-done).  

Thanks to @davefrey  for helping to develop this plan :+1:

**Comment by oliverbarnes** [comment]
Closing this as the most basic UX improvements have been done, and the remainder can be tracked as part of the overall integration work: https://github.com/liquidvotingio/decidim-instance/issues/2
